version: '3'

services:
  postgres-compose:
    image: postgres:15.1-alpine
    container_name: pg-compose
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
